<a href="https://colab.research.google.com/github/karino2/tegashiki/blob/master/crohme2019_preprocess.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Crohme 2019 data preprocess**

In [0]:
import os
import datetime
import pickle
import gzip
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


Upload 3 zip manually

- Train.zip
- Test.zip
- valid.zip

from Task1_onlineRec/MainTask_formula/

In [0]:
!unzip valid.zip

In [0]:
one_file="valid/TestEM2014GT_INKMLs/37_em_32.inkml"

In [0]:
one_file="valid/TestEM2014GT_INKMLs/31_em_178.inkml"

In [0]:
one_file = "valid/TestEM2014GT_INKMLs/18_em_0.inkml"

In [0]:
os.path.basename(one_file)

'18_em_0.inkml'

In [0]:
with open(one_file, "r") as f:
  text = f.read()

In [0]:
print(text)

<ink xmlns="http://www.w3.org/2003/InkML">
<traceFormat>
<channel name="X" type="decimal"/>
<channel name="Y" type="decimal"/>
</traceFormat>
<annotation type="age">37</annotation>
<annotation type="gender">F</annotation>
<annotation type="hand">R</annotation>
<annotation type="writer">31</annotation>
<annotation type="truth">$q+w\;$</annotation>
<annotation type="UI">ISICAL_2014_F31_E178</annotation>
<annotation type="copyright">ISICAL_2014</annotation>
<annotationXML type="truth" encoding="Content-MathML">
	<math xmlns='http://www.w3.org/1998/Math/MathML'>
		<mrow>
			<mi xml:id="q_1">q</mi>
			<mrow>
				<mo xml:id="+_1">+</mo>
				<mrow>
					<mi xml:id="w_1">w</mi>
				</mrow>
			</mrow>
		</mrow>
	</math>
</annotationXML>
<trace id="0">
365 186, 365 186, 365 186, 365 184, 365 183, 365 183, 365 183, 365 183, 365 182, 365 182, 365 182, 365 182, 365 182, 365 182, 365 182, 365 182, 365 182, 365 182, 364 184, 364 188, 364 188, 364 188, 364 188, 365 196, 365 196, 365 196, 365 206, 363 

In [0]:
with open(one_file, "r") as f:
  lines = [line.rstrip("\n") for line in f]

In [0]:
import re

In [0]:
LATEX_PAT = re.compile(r'<annotation type="truth">(.*?)</annotation>',re.MULTILINE|re.DOTALL)

In [0]:
temp="$a_0+a_1x+a_2x^2+\\cdots"

In [0]:
temp.strip("$")

'a_0+a_1x+a_2x^2+\\cdots'

In [0]:
text

'<ink xmlns="http://www.w3.org/2003/InkML">\n<traceFormat>\n<channel name="X" type="decimal"/>\n<channel name="Y" type="decimal"/>\n</traceFormat>\n<annotation type="age">41</annotation>\n<annotation type="gender">M</annotation>\n<annotation type="hand">R</annotation>\n<annotation type="writer">37</annotation>\n<annotation type="truth">$a_0+a_1x+a_2x^2+\\cdots</annotation>\n<annotation type="UI">ISICAL_2014_F37_E32</annotation>\n<annotation type="copyright">ISICAL_2014</annotation>\n<annotationXML type="truth" encoding="Content-MathML">\n\t<math xmlns=\'http://www.w3.org/1998/Math/MathML\'>\n\t\t<mrow>\n\t\t\t<msub>\n\t\t\t\t<mi xml:id="a_1">a</mi>\n\t\t\t\t<mn xml:id="0_1">0</mn>\n\t\t\t</msub>\n\t\t\t<mrow>\n\t\t\t\t<mo xml:id="+_1">+</mo>\n\t\t\t\t<mrow>\n\t\t\t\t\t<msub>\n\t\t\t\t\t\t<mi xml:id="a_2">a</mi>\n\t\t\t\t\t\t<mn xml:id="1_1">1</mn>\n\t\t\t\t\t</msub>\n\t\t\t\t\t<mrow>\n\t\t\t\t\t\t<mi xml:id="x_1">x</mi>\n\t\t\t\t\t\t<mrow>\n\t\t\t\t\t\t\t<mo xml:id="+_2">+</mo>\n\t\t\t

In [0]:
pickup_latex(text)

'a_0+a_1x+a_2x^2+\\cdots'

In [0]:
def pickup_latex(text):
  return LATEX_PAT.search(text).group(1).strip().strip("$")

In [0]:
STROKE_PAT= re.compile(r'<trace [^>]*>(.*?)</trace>',re.MULTILINE|re.DOTALL)

In [0]:
def pickup_traces(text):
  res = []
  pos = 0
  match = STROKE_PAT.search(text)
  while(match != None):
    res.append(match.group(1).strip("\n"))
    pos = match.end()
    match = STROKE_PAT.search(text, pos)
  return res
  

In [0]:
STROKE_PAT.search

In [0]:
pickup_traces(text)

['34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 35 53, 35 53, 35 53, 35 53, 35 52, 35 52, 35 52, 35 52, 35 52, 35 52, 35 52, 35 52, 35 52, 35 52, 35 52, 35 52, 35 52, 35 52, 35 52, 35 52, 35 52, 35 52, 35 52, 36 50, 36 50, 36 50, 36 50, 37 49, 37 49, 37 49, 37 49, 37 49, 37 49, 37 49, 37 49, 37 49, 37 49, 37 49, 37 49, 37 49, 37 49, 37 49, 37 49, 37 49, 39 49, 39 49, 39 49, 40 48, 40 48, 40 48, 40 48, 40 48, 40 48, 40 48, 40 48, 40 48, 40 48, 40 48, 40 48, 40 48, 40 48, 40 48, 42 47, 42 47, 42 47, 42 47, 42 47, 42 47, 42 47, 42 47, 44 47, 44 47, 44 47, 44 47, 44 47, 45 47, 45 47, 45 47, 45 47, 45 47, 45 47, 46 47, 46 47, 46 47, 46 47, 46 47, 46 47, 46 47, 46 47, 46 47, 46 47, 46 47, 46 4

In [0]:
def file2dict(fpath):
  with open(fpath, "r") as f:
    text = f.read()
  latex = pickup_latex(text)
  strokes = pickup_traces(text)
  return {"latex": latex, "strokes":strokes, "path": fpath}

In [0]:
dic = file2dict(one_file)

In [0]:
dic

{'latex': 'x_k xx_k + y_k yx_k',
 'path': 'valid/TestEM2014GT_INKMLs/18_em_0.inkml',
 'strokes': ['34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 35 53, 35 53, 35 53, 35 53, 35 52, 35 52, 35 52, 35 52, 35 52, 35 52, 35 52, 35 52, 35 52, 35 52, 35 52, 35 52, 35 52, 35 52, 35 52, 35 52, 35 52, 35 52, 35 52, 36 50, 36 50, 36 50, 36 50, 37 49, 37 49, 37 49, 37 49, 37 49, 37 49, 37 49, 37 49, 37 49, 37 49, 37 49, 37 49, 37 49, 37 49, 37 49, 37 49, 37 49, 39 49, 39 49, 39 49, 40 48, 40 48, 40 48, 40 48, 40 48, 40 48, 40 48, 40 48, 40 48, 40 48, 40 48, 40 48, 40 48, 40 48, 40 48, 42 47, 42 47, 42 47, 42 47, 42 47, 42 47, 42 47, 42 47, 44 47, 44 47, 44 47, 44 47, 44 47, 45 47, 45 47, 45 47, 45 47

In [0]:
import glob

In [0]:
valid_dicts=[]

for file in glob.glob("valid/**/*.inkml"):
  valid_dicts.append(file2dict(file))

In [0]:
!unzip Train.zip

In [0]:
train_dicts=[]

for file in glob.glob("Train/INKMLs/**/*.inkml"):
  train_dicts.append(file2dict(file))

In [0]:
len(train_dicts)

9993

In [0]:
from google.colab import auth
auth.authenticate_user()

In [0]:
dump_and_send(train_dicts, "crohme2019_train_dict.pkl.gz")

Copying file://crohme2019_train_dict.pkl.gz [Content-Type=application/octet-stream]...
-
Operation completed over 1 objects/20.5 MiB.                                     


In [0]:
dump_and_send(valid_dicts, "crohme2019_valid_dict.pkl.gz")

Copying file://crohme2019_valid_dict.pkl.gz [Content-Type=application/octet-stream]...
/ [1 files][  1.3 MiB/  1.3 MiB]                                                
Operation completed over 1 objects/1.3 MiB.                                      


### Data investigation

In [0]:
valid_dicts[1]

{'latex': 'q+w\\;',
 'path': 'valid/TestEM2014GT_INKMLs/31_em_178.inkml',
 'strokes': ['365 186, 365 186, 365 186, 365 184, 365 183, 365 183, 365 183, 365 183, 365 182, 365 182, 365 182, 365 182, 365 182, 365 182, 365 182, 365 182, 365 182, 365 182, 364 184, 364 188, 364 188, 364 188, 364 188, 365 196, 365 196, 365 196, 365 206, 363 217, 363 217, 363 217, 362 231, 362 231, 362 231, 361 244, 360 260, 360 260, 360 260, 360 260, 360 260, 360 260, 360 275, 360 275, 360 275, 359 286, 359 286, 359 292, 359 292, 359 295, 359 295, 359 295, 359 297, 359 297, 359 297, 359 297, 359 297, 359 294, 359 294, 359 294, 359 288, 359 288, 359 288, 359 288, 359 288, 359 288, 359 278, 359 267, 359 267, 359 267, 359 256, 358 248, 358 248, 358 248, 358 243, 358 243, 358 243, 358 243, 357 238, 357 238, 357 238, 354 234, 352 229, 352 229, 352 229, 351 226, 347 222, 347 222, 345 220, 345 220, 345 220, 345 220, 345 220, 343 218, 341 217, 341 217, 341 217, 339 216, 339 216, 339 216, 337 216, 335 216, 335 216, 335

In [0]:
[(dic["latex"], dic["path"]) for dic in valid_dicts]

[('C_t = C + C = 2C', 'valid/TestEM2014GT_INKMLs/29_em_163.inkml'),
 ('q+w\\;', 'valid/TestEM2014GT_INKMLs/31_em_178.inkml'),
 (' \\frac {\\log _ {b} x} {\\log _ {b} a} ',
  'valid/TestEM2014GT_INKMLs/RIT_2014_192.inkml'),
 ('\\sqrt{v^2-{v_v}^2}=\\frac {{v_v}^2}{\\sqrt{v^2-{v_v}^2}}',
  'valid/TestEM2014GT_INKMLs/502_em_16.inkml'),
 ('\\lambda (t) = \\lambda_0 (1-e ^{-\\frac{t}{\\lambda}})',
  'valid/TestEM2014GT_INKMLs/520_em_466.inkml'),
 (' (a (b ^ {2})) + (d ^ {3}) ',
  'valid/TestEM2014GT_INKMLs/RIT_2014_147.inkml'),
 ('R_\\mathrm{L}', 'valid/TestEM2014GT_INKMLs/502_em_12.inkml'),
 ('\\frac{8993}{7873}', 'valid/TestEM2014GT_INKMLs/519_em_440.inkml'),
 (' a,\\ldots,f ', 'valid/TestEM2014GT_INKMLs/512_em_295.inkml'),
 ('\\int \\frac{dx}{x} + \\int \\frac{2}{x+1} dx',
  'valid/TestEM2014GT_INKMLs/510_em_100.inkml'),
 ('\\frac{x^2+13x+40}{2x^3+27x^2+111x+140}',
  'valid/TestEM2014GT_INKMLs/29_em_173.inkml'),
 (' \\{ 7, 7 \\} = \\{ 7 \\} ', 'valid/TestEM2014GT_INKMLs/RIT_2014_73.inkml'

In [0]:
"ika" in "hogeikahoge"

True

In [0]:
[(dic["latex"], dic["path"]) for dic in train_dicts if "TestINKMLGT_2012" in dic["path"]]

[('( a^2 + b^2 ) ( c^2 + d^2 ) \\geq ( a c + b d )^2',
  'Train/INKMLs/TestINKMLGT_2012/KME1G3_0_sub_29.inkml'),
 ('( x^3 - x^2 - x ) ( 2 x - 7 )',
  'Train/INKMLs/TestINKMLGT_2012/KME2G3_6_sub_15.inkml'),
 ('\\int ( 2^x - 3 e^x ) d x',
  'Train/INKMLs/TestINKMLGT_2012/KME2G3_4_sub_61.inkml'),
 ('z = 4', 'Train/INKMLs/TestINKMLGT_2012/formulaire041-equation001.inkml'),
 ('\\pi^{-1}(b)',
  'Train/INKMLs/TestINKMLGT_2012/formulaire047-equation046.inkml'),
 ('-(y_1 + y_2)(y_3 + y_4)',
  'Train/INKMLs/TestINKMLGT_2012/formulaire042-equation026.inkml'),
 ('g(x_1,x_2,x_3)',
  'Train/INKMLs/TestINKMLGT_2012/formulaire042-equation019.inkml'),
 ('y_1(z)&lt;y(z)&lt;y_2(z)',
  'Train/INKMLs/TestINKMLGT_2012/002-equation011.inkml'),
 ('\\int_0^{\\frac \\pi 2} \\{ ( \\cos x + e^x ) - ( e^x - \\cos x ) \\} d x',
  'Train/INKMLs/TestINKMLGT_2012/KME2G3_1_sub_66.inkml'),
 ('\\lim_{x \\rightarrow 0} ( 1 + x )^{\\frac 1 x}',
  'Train/INKMLs/TestINKMLGT_2012/KME2G3_1_sub_48.inkml'),
 ('mg(3-2\\cos \\thet

In [0]:
len([(dic["latex"], dic["path"]) for dic in train_dicts if "TestINKMLGT_2012" in dic["path"]])

488

In [0]:
for file in glob.glob("Train/**/*.inkml"):
  print(file)

In [0]:
for file in glob.glob("Train/INKMLs/**/*.inkml"):
  print(file)

Train/LGs/Test2013_LG
Train/LGs/Test2012_LG
Train/LGs/Train2014_LG
Train/LGs/Readme.txt
Train/INKMLs/Train_2014
Train/INKMLs/TestINKMLGT_2013
Train/INKMLs/TestINKMLGT_2012


### Data load

In [0]:
from google.colab import auth
auth.authenticate_user()


For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.



In [0]:
def get_if_necessary(fname):
  if os.path.exists(fname):
    return
  !gsutil cp gs://karino2-tegashiki/dataset/{fname} {fname}

def get_and_load(fname):
  get_if_necessary(fname)
  with gzip.open(fname,'rb') as f:
    return pickle.load(f)  
  
def dump_and_send(obj, fname):
  with gzip.open(fname,'wb') as f:
    pickle.dump(obj, f)
  !gsutil cp {fname} gs://karino2-tegashiki/dataset/

In [0]:
get_if_necessary("dictionary2.txt.gz")
with gzip.open("dictionary2.txt.gz", "rt") as f:
  dict_tokens = [tup[0] for tup in [line.rstrip().split() for line in f]]

Copying gs://karino2-tegashiki/dataset/dictionary2.txt.gz...
/ [1 files][  546.0 B/  546.0 B]                                                
Operation completed over 1 objects/546.0 B.                                      


## Tokenize

In [0]:
train_dicts = get_and_load("crohme2019_train_dict.pkl.gz")

Copying gs://karino2-tegashiki/dataset/crohme2019_train_dict.pkl.gz...
/ [1 files][ 20.5 MiB/ 20.5 MiB]                                                
Operation completed over 1 objects/20.5 MiB.                                     


In [0]:
valid_dicts = get_and_load("crohme2019_valid_dict.pkl.gz")

Copying gs://karino2-tegashiki/dataset/crohme2019_valid_dict.pkl.gz...
/ [1 files][  1.3 MiB/  1.3 MiB]                                                
Operation completed over 1 objects/1.3 MiB.                                      


### Data cleansing

In [0]:
import re

In [0]:
EXCLAMATION_BEG_PAT=re.compile(r'^\\!(.*)')
EXCLAMATION_END_PAT=re.compile(r'(.*)\\!$')
SPACE_END_PAT=re.compile(r'(.*)\\ $')


In [0]:
def filter_trim_exclamation(target):
  tmp = re.sub(EXCLAMATION_BEG_PAT, r'\1',target)
  tmp = re.sub(EXCLAMATION_END_PAT, r'\1', tmp)
  tmp = re.sub(SPACE_END_PAT, r'\1', tmp)
  return tmp
  # return target.strip("\\!").rstrip("\\ ")

In [0]:
MATH_RM_PAT = re.compile(r'\\mathrm{([^}]*?)}')

In [0]:
def filter_mathrm(target):
  return re.sub(MATH_RM_PAT, r'\1', target)

In [0]:
MBOX_PAT = re.compile(r'\\mbox *{([^}]*?)}')

In [0]:
def filter_mbox(target):
  return re.sub(MBOX_PAT, r'\1', target)

In [0]:
LEFT_PAREN_PAT=re.compile(r'\\left *\(')
RIGHT_PAREN_PAT=re.compile(r'\\right *\)')
LEFT_SBRACKET_PAT=re.compile(r'\\left *\[')
RIGHT_SBRACKET_PAT=re.compile(r'\\right *\]')


In [0]:
def filter_left_right_paren(target):
  tmp = re.sub(LEFT_PAREN_PAT, '(', target)
  tmp =re.sub(RIGHT_PAREN_PAT, ')', tmp)
  tmp = re.sub(LEFT_SBRACKET_PAT, '[', tmp)
  tmp =re.sub(RIGHT_SBRACKET_PAT, ']', tmp)

  return tmp.replace("\\lbrack", "[").replace("\\rbrack", "]")

In [0]:
def filter_lg(target):
  return target.replace("&gt;", ">").replace("&lt;", "<").replace("\\gt ", "> ").replace("\\lt ", "< ")

In [0]:
filter_lg('\\lim_{x \\rightarrow -\\infty} p_2(x)&gt;0 \\!')

'\\lim_{x \\rightarrow -\\infty} p_2(x)>0 \\!'

In [0]:
def filter_all(target):
  return filter_lg(filter_left_right_paren(filter_mbox(filter_mathrm(filter_trim_exclamation(target)))))

### Cleansing check

In [0]:
import unittest

In [0]:
def run_test(klass):
  suite = unittest.TestLoader().loadTestsFromTestCase(klass)
  unittest.TextTestRunner().run(suite)

In [0]:
re.sub(LEFT_PAREN_PAT, '(', '{ - \\left ( v \\right ) }').replace("\\right)", ")")

'{ - ( v \\right ) }'

In [0]:
filter_left_right_paren('{ - \\left ( v \\right ) }')

'{ - ( v \\right ) }'

In [0]:
class TestFilter(unittest.TestCase):
  def verify_filter(self, input, expect, func):
    actual = func(input)
    self.assertEqual(expect, actual)
  def test_mbox(self):
    def vm(input, expect):
      self.verify_filter(input, expect, filter_mbox)
    vm('\\mbox { y }', " y ")
    vm('\\mbox { k } \\left ( \\mbox { B } \\right )', ' k  \\left (  B  \\right )')
    vm('\\int e ^ { - z ^ 2 } d z = \\mbox { erf } \\left ( z \\right )', '\\int e ^ { - z ^ 2 } d z =  erf  \\left ( z \\right )')
  def test_paren(self):
    def pn(input, expect):
      self.verify_filter(input, expect, filter_left_right_paren)
    pn('{ - \\left ( v \\right ) }', '{ - ( v ) }')
    pn('u(x, y) = B \\sin(n \\pi x)\\left(e^{n \\pi y} - e^{-n \\pi y}\\right)', 'u(x, y) = B \\sin(n \\pi x)(e^{n \\pi y} - e^{-n \\pi y})')
    pn('\\left ( {  G  -  V  } \\right )', '( {  G  -  V  } )')
    pn('\\left [ \\left [  o  \\right ] \\right ]', '[ [  o  ] ]')
  def test_lg(self):
    def lg(input, expect):
      self.verify_filter(input, expect, filter_lg)
    lg('\\lim_{x \\rightarrow -\\infty} p_2(x)&gt;0 \\!', '\\lim_{x \\rightarrow -\\infty} p_2(x)>0 \\!')
    lg('a x + b \\lt c', 'a x + b < c')
    lg('1234 + 5678 \\gt 90', '1234 + 5678 > 90')

    
run_test(TestFilter)

...
----------------------------------------------------------------------
Ran 3 tests in 0.006s

OK


In [0]:
t# [tup for tup in train_failed[0:100]]

In [0]:
def conb(target):
  return filter_lg(filter_left_right_paren(filter_mbox(target)))

In [0]:
train_tokenized = [(dic["latex"], conb(dic["latex"]), tokenizer.tokenize_all(conb(dic["latex"])), dic["strokes"]) for dic in train_dicts]
train_failed = [(tup[1], tup[0]) for tup in train_tokenized if not tup[2][0]]
train_success = [(tup[1], tup[0]) for tup in train_tokenized if tup[2][0]]

In [0]:
train_tokenized = [(dic["latex"], filter_all(dic["latex"]), tokenizer.tokenize_all(filter_all(dic["latex"])), dic["strokes"]) for dic in train_dicts]
train_failed = [(tup[1], tup[0]) for tup in train_tokenized if not tup[2][0]]
train_success = [(tup[1], tup[0]) for tup in train_tokenized if tup[2][0]]

In [0]:
len(train_tokenized)

9993

In [0]:
len(train_failed)

131

In [0]:
valid_tokenized = [(dic["latex"], filter_all(dic["latex"]), tokenizer.tokenize_all(filter_all(dic["latex"])), dic["strokes"]) for dic in valid_dicts]
valid_failed = [(tup[1], tup[0]) for tup in valid_tokenized if not tup[2][0]]
valid_success = [(tup[1], tup[0]) for tup in valid_tokenized if tup[2][0]]

In [0]:
len(valid_success), len(valid_failed), len(valid_tokenized)

(958, 28, 986)

In [0]:
# valid_success[0:20]

### Tokenize

In [0]:
len(dict_tokens)

113

In [0]:
tokens = dict_tokens

In [0]:
one_char_tokens = [tk for tk in tokens if len(tk) == 1]

In [0]:
multi_char_tokens = [tk for tk in tokens if len(tk) != 1]

In [0]:
# Drop special token like <eos>
multi_char_tokens = multi_char_tokens[:-2]

In [0]:
class Tokenizer:
  def __init__(self, one_tokens, multi_tokens):
    self.one_tokens = set(one_tokens)
    self.multi_tokens = multi_tokens
    self.target = ""
    self.pos = 0
    
  def set_target(self, target):
    self.pos=0
    self.target = target
  def skip_space(self):
    if self.is_end():
      return
    while (not self.is_end()) and self.target[self.pos] == ' ':
      self.pos += 1
  def go_next(self, token):
    self.pos += len(token)
    self.skip_space()
    return token
  def is_end(self):
    return len(self.target) == self.pos
  def tokenize_one(self):
    self.skip_space()
    multi = [tk for tk in self.multi_tokens if self.target.startswith(tk, self.pos)]
    if(len(multi) != 0):
      return self.go_next(multi[0])
    onech = self.target[self.pos]
    if(onech in self.one_tokens):
      return self.go_next(onech)
    self.unknown = onech
    raise Exception("Unknown token {}".format(onech))
  def tokenize_all_unsafe(self, target):
    self.set_target(target)
    self.skip_space()
    res = []
    while not self.is_end():
      res.append(self.tokenize_one())
    return True, res
  def tokenize_all(self, target):    
    try:
      return self.tokenize_all_unsafe(target)
    except:
      return False, None
      

In [0]:
tokenizer = Tokenizer(one_char_tokens, multi_char_tokens)

In [0]:
valid_tokenized = [(dic["path"], dic["latex"], filter_all(dic["latex"]), tokenizer.tokenize_all(filter_all(dic["latex"])), dic["strokes"]) for dic in valid_dicts]

In [0]:
train_tokenized = [(dic["path"], dic["latex"], filter_all(dic["latex"]), tokenizer.tokenize_all(filter_all(dic["latex"])), dic["strokes"]) for dic in train_dicts]

In [0]:
train_failed = [(tup[1], tup[0]) for tup in train_tokenized if not tup[3][0]]

In [0]:
train_success = [( tup[0], tup[1], tup[2], tup[3][1], tup[4]) for tup in train_tokenized if tup[3][0]]

In [0]:
len(train_success), len(train_failed), len(train_dicts)

(9862, 131, 9993)

In [0]:
dump_and_send(train_success[0:100], "crohme2019_fixed_train_tokenized_small.pkl.gz")

Copying file://crohme2019_fixed_train_tokenized_small.pkl.gz [Content-Type=application/octet-stream]...
/ [1 files][218.1 KiB/218.1 KiB]                                                
Operation completed over 1 objects/218.1 KiB.                                    


In [0]:
dump_and_send(train_success, "crohme2019_fixed_train_tokenized.pkl.gz")

Copying file://crohme2019_fixed_train_tokenized.pkl.gz [Content-Type=application/octet-stream]...
-
Operation completed over 1 objects/20.5 MiB.                                     


In [0]:
valid_success = [( tup[0], tup[1], tup[2], tup[3][1], tup[4]) for tup in valid_tokenized if tup[3][0]]

In [0]:
len(valid_success), len(valid_dicts)

(958, 986)

In [0]:
dump_and_send(valid_success, "crohme2019_fixed_valid_tokenized.pkl.gz")

Copying file://crohme2019_fixed_valid_tokenized.pkl.gz [Content-Type=application/octet-stream]...
/ [1 files][  1.2 MiB/  1.2 MiB]                                                
Operation completed over 1 objects/1.2 MiB.                                      


## Setup training data

In [0]:
[tup[3] for tup in valid_success[0:100]]

[['C', '_', 't', '=', 'C', '+', 'C', '=', '2', 'C'],
 ['\\frac',
  '{',
  '\\log',
  '_',
  '{',
  'b',
  '}',
  'x',
  '}',
  '{',
  '\\log',
  '_',
  '{',
  'b',
  '}',
  'a',
  '}'],
 ['\\sqrt',
  '{',
  'v',
  '^',
  '2',
  '-',
  '{',
  'v',
  '_',
  'v',
  '}',
  '^',
  '2',
  '}',
  '=',
  '\\frac',
  '{',
  '{',
  'v',
  '_',
  'v',
  '}',
  '^',
  '2',
  '}',
  '{',
  '\\sqrt',
  '{',
  'v',
  '^',
  '2',
  '-',
  '{',
  'v',
  '_',
  'v',
  '}',
  '^',
  '2',
  '}',
  '}'],
 ['\\lambda',
  '(',
  't',
  ')',
  '=',
  '\\lambda',
  '_',
  '0',
  '(',
  '1',
  '-',
  'e',
  '^',
  '{',
  '-',
  '\\frac',
  '{',
  't',
  '}',
  '{',
  '\\lambda',
  '}',
  '}',
  ')'],
 ['(',
  'a',
  '(',
  'b',
  '^',
  '{',
  '2',
  '}',
  ')',
  ')',
  '+',
  '(',
  'd',
  '^',
  '{',
  '3',
  '}',
  ')'],
 ['R', '_', 'L'],
 ['\\frac', '{', '8', '9', '9', '3', '}', '{', '7', '8', '7', '3', '}'],
 ['a', ',', '\\ldots', ',', 'f'],
 ['\\int',
  '\\frac',
  '{',
  'd',
  'x',
  '}',
  '{',
  'x',

In [0]:
valid_success[0][3]

['248 105, 248 105, 248 105, 248 105, 248 105, 248 105, 248 105, 248 105, 248 105, 248 105, 248 105, 248 105, 248 105, 248 105, 248 105, 248 105, 248 105, 248 105, 248 105, 248 105, 248 105, 248 105, 248 105, 248 105, 246 105, 246 105, 246 105, 246 105, 246 105, 246 105, 246 105, 246 105, 246 105, 246 105, 246 105, 246 105, 246 105, 246 105, 246 105, 246 105, 246 105, 246 105, 246 105, 246 105, 245 105, 245 105, 245 105, 245 105, 245 105, 244 103, 244 103, 244 103, 244 103, 244 103, 244 103, 243 103, 243 103, 243 103, 243 103, 241 102, 241 102, 241 102, 238 102, 234 102, 234 102, 234 102, 230 102, 230 102, 225 103, 225 103, 222 104, 222 104, 222 104, 219 104, 219 104, 219 104, 216 105, 210 108, 210 108, 210 108, 210 108, 210 108, 206 110, 201 113, 201 113, 201 113, 201 113, 201 113, 196 117, 196 117, 194 119, 194 119, 191 123, 191 123, 191 123, 189 126, 189 126, 189 126, 186 131, 183 136, 183 136, 181 142, 181 142, 181 142, 180 146, 179 149, 179 149, 179 149, 179 149, 179 149, 178 153,

In [0]:
def stroke_length(strokearr):
  # sum_of_strokelen + stroke_sep(or EndOfToken)
  return sum(len(stroke.split(",")) for stroke in strokearr)+len(strokearr)

In [0]:
max(stroke_length(one[3]) for one in train_success)

NameError: ignored

In [0]:
max(stroke_length(one[3]) for one in valid_success)

6620

In [0]:
val_lens = [stroke_length(one[3]) for one in valid_success]

In [0]:
len([elm for elm in val_lens if elm <= 2773 ])

917

In [0]:
len(val_lens)

952

Stroke of validation seems much larger than training set.
We need to pad for max seq length.
I think too large padding make learning slow and we don't need so much validation set.

So I use stroke length smaller than MAX_STROKE_SEQ_LEN of training set.

In [0]:
MAX_STROKE_SEQ_LEN=2773

NORMALIZE_WIDTH=2000

In [0]:
INPUT_TYPE_POINT=1
INPUT_TYPE_SEP=2
INPUT_TYPE_END=0

# (x, y, TYPE)
INPUT_TYPE_DIM=3

In [0]:
training_list = train_success[0:100]

### Setup stroke inupt

In [0]:
def strokearr2poslislis(strokearr):
  res = []
  
  for line in strokearr:
    res.append([(float(pair[0]),float(pair[1])) for pair in [pos.strip().split(" ") for pos in line.split(",")]])
  return res

In [0]:
def normalize_poslislis(poslislis):
    maxval = max(max(tup) for poslis in poslislis for tup in poslis)
    ratio = NORMALIZE_WIDTH/maxval
    return [(ratio*np.array(poslis)).astype(int) for poslis in poslislis]
    

In [0]:
def poslislis2vec(poslislis):
  """To list of 3D vector (x, y, TYPE).
  put (0, 0, INPUT_TYPE_SEP) between stroke.
  put (0, 0, INPUT_TYPE_END) at end.
  """
  res = None
  for one_stroke in poslislis:
    # onestoke (size, 2)
    widen = INPUT_TYPE_POINT*np.ones((one_stroke.shape[0], 3), dtype=int)
    widen[:, :-1] = one_stroke

    # Compare to None cause broadcast for np.array.
    if type(res) != np.ndarray:
      res = np.concatenate((widen, np.array([[0, 0, INPUT_TYPE_SEP]])))
    else:
      res = np.concatenate((res, widen, np.array([[0, 0, INPUT_TYPE_SEP]])))
  res[-1, 2] = INPUT_TYPE_END
  return res

In [0]:
def training_list_to_stroke_input_data(training_list):
  stroke_input_data = np.zeros(
    (len(training_list), STROKE_MAX_SEQ_LEN, INPUT_TYPE_DIM),
    dtype='int')
  for i, tup in enumerate(training_list):
    lislis = strokearr2poslislis(tup[3])
    lislis = normalize_poslislis(lislis)
    vec = poslislis2vec(lislis)
    stroke_input_data[i,0:vec.shape[0], : ] = vec
  return stroke_input_data

In [0]:
stroke_input = training_list_to_stroke_input_data(training_list)

In [0]:
stroke_input.shape

(100, 2773, 3)

In [0]:
stroke_input[0, 0:5, :]

array([[1666, 3309,    1],
       [1666, 3308,    1],
       [1668, 3308,    1],
       [1671, 3309,    1],
       [1676, 3307,    1]])

### Setup decoder input and target

## Try and Error

In [0]:
one_char_tokens

['/',
 '(',
 ',',
 '0',
 '8',
 '<',
 'H',
 'L',
 'P',
 'T',
 'X',
 'd',
 'h',
 'l',
 'p',
 't',
 'x',
 '|',
 "'",
 '+',
 '3',
 '7',
 'C',
 'G',
 'S',
 '[',
 '_',
 'c',
 'z',
 'g',
 'k',
 'o',
 's',
 'w',
 '{',
 '.',
 '2',
 '6',
 '4',
 'B',
 'F',
 'N',
 'R',
 'V',
 '^',
 'b',
 'f',
 'j',
 'n',
 'r',
 'v',
 '>',
 '!',
 ')',
 '-',
 '1',
 '5',
 '9',
 '=',
 'A',
 'E',
 'I',
 'M',
 'Y',
 ']',
 'a',
 'e',
 'i',
 'm',
 'q',
 'u',
 'y',
 '}']

In [0]:
lislis = strokearr2poslislis(training_list[0][3])

In [0]:
vec.shape[0]

126

In [0]:
vec.shape[1]

3

In [0]:
nomlis = normalize_poslislis(lislis)

In [0]:
nomlis

In [0]:
vec = poslislis2vec(nomlis)

In [0]:
vec.shape

(126, 3)

In [0]:
vec[0:5, :]

array([[1666, 3309,    1],
       [1666, 3308,    1],
       [1668, 3308,    1],
       [1671, 3309,    1],
       [1676, 3307,    1]])

In [0]:
stroke_input.shape

(100, 2773, 3)

In [0]:
stroke_input[0, 120:130, :]

array([[175,  13,   1],
       [176,  14,   1],
       [181,  13,   1],
       [193,  15,   1],
       [208,  16,   1],
       [  0,   0,   0],
       [  0,   0,   0],
       [  0,   0,   0],
       [  0,   0,   0],
       [  0,   0,   0]], dtype=uint8)

In [0]:
stroke_input[0, :, 0].max()

249

In [0]:
training_list[0]

('Train/INKMLs/Train_2014/formulaire028-equation067.inkml',
 'f_2, g_2',
 ['f', '_', '2', ',', 'g', '_', '2'],
 ['10.7816 21.4071, 10.7776 21.3991, 10.7896 21.4031, 10.8097 21.4071, 10.8418 21.3951, 10.9019 21.375, 10.9782 21.3309, 11.0705 21.2867, 11.1226 21.2386, 11.1587 21.1904, 11.1708 21.1342, 11.1708 21.066, 11.1427 20.9858, 11.1066 20.9296, 11.0825 20.9176, 11.0745 20.9216, 11.0624 20.9336, 11.0464 20.9978, 11.0263 21.062, 11.0303 21.1503, 11.0384 21.2426, 11.0544 21.3268, 11.0705 21.4392, 11.0785 21.5235, 11.0865 21.5877, 11.0865 21.6398, 11.0905 21.6639, 11.0945 21.688, 11.0905 21.688',
  '11.0063 21.4793, 11.0103 21.4753, 11.0143 21.4753, 11.0344 21.4713, 11.0865 21.4673, 11.1467 21.4633, 11.2591 21.4472',
  '11.5199 21.4472, 11.4958 21.4472, 11.4757 21.4472, 11.4557 21.4352, 11.4476 21.4352, 11.4396 21.4151, 11.4436 21.3991, 11.4517 21.387, 11.4677 21.367, 11.4958 21.363, 11.5159 21.375, 11.5439 21.383, 11.552 21.4071, 11.552 21.4272, 11.5319 21.4352, 11.4918 21.4753, 11.447

In [0]:
type(np.zeros((1))) == np.ndarray

True

In [0]:
type(np.zeros((1)))

numpy.ndarray

In [0]:
tmp = normalize_poslislis(res)

In [0]:
res_tokens = poslislis2vec(tmp)

In [0]:
res_tokens.shape

(433, 3)

In [0]:
res_tokens[-10:]

array([[1994, 3458,    1],
       [1997, 3451,    1],
       [2000, 3441,    1],
       [2000, 3432,    1],
       [1998, 3426,    1],
       [1995, 3418,    1],
       [1992, 3412,    1],
       [1985, 3404,    1],
       [1974, 3398,    1],
       [   0,    0,    0]])

In [0]:
tmp[0].shape

(11, 2)

In [0]:
tmp[0][:, :, np.newaxis] = INPUT_TYPE_POINT

In [0]:
tmp[0]

array([[1146, 3363],
       [1144, 3364],
       [1142, 3366],
       [1136, 3371],
       [1131, 3378],
       [1126, 3387],
       [1122, 3393],
       [1119, 3397],
       [1116, 3401],
       [1115, 3402],
       [1114, 3402]])

In [0]:
tmp[0].shape[0]

11

In [0]:
widen = INPUT_TYPE_POINT*np.ones((tmp[0].shape[0], 3), dtype=int)

In [0]:
widen.shape

(11, 3)

In [0]:
widen[:, :-1] = tmp[0]

In [0]:
widen

array([[1146, 3363,    1],
       [1144, 3364,    1],
       [1142, 3366,    1],
       [1136, 3371,    1],
       [1131, 3378,    1],
       [1126, 3387,    1],
       [1122, 3393,    1],
       [1119, 3397,    1],
       [1116, 3401,    1],
       [1115, 3402,    1],
       [1114, 3402,    1]])

In [0]:
np.array([[0, 0, INPUT_TYPE_SEP]])

array([[0, 0, 2]])

In [0]:
widen

array([[1146, 3363,    1],
       [1144, 3364,    1],
       [1142, 3366,    1],
       [1136, 3371,    1],
       [1131, 3378,    1],
       [1126, 3387,    1],
       [1122, 3393,    1],
       [1119, 3397,    1],
       [1116, 3401,    1],
       [1115, 3402,    1],
       [1114, 3402,    1]])

In [0]:
np.concatenate((widen, np.array([[0, 0, INPUT_TYPE_SEP]])))

array([[1146, 3363,    1],
       [1144, 3364,    1],
       [1142, 3366,    1],
       [1136, 3371,    1],
       [1131, 3378,    1],
       [1126, 3387,    1],
       [1122, 3393,    1],
       [1119, 3397,    1],
       [1116, 3401,    1],
       [1115, 3402,    1],
       [1114, 3402,    1],
       [   0,    0,    2]])

In [0]:
tmp[0][:, 2]

IndexError: ignored

In [0]:
widen = tmp[0]

In [0]:
widen[:, 2] = INPUT_TYPE_POINT

IndexError: ignored

In [0]:
widen.shape

(11, 1, 2)

In [0]:
np.expand_dims(tmp[0], axis=2)

array([[[1146],
        [3363]],

       [[1144],
        [3364]],

       [[1142],
        [3366]],

       [[1136],
        [3371]],

       [[1131],
        [3378]],

       [[1126],
        [3387]],

       [[1122],
        [3393]],

       [[1119],
        [3397]],

       [[1116],
        [3401]],

       [[1115],
        [3402]],

       [[1114],
        [3402]]])

In [0]:
.expand_dims(axis=2)

AttributeError: ignored

In [0]:
tmp = np.array((1.2, 2.3, 3.4))

In [0]:
tmp.tmp.astype

In [0]:
[(123*np.array(lis)).astype(int) for lis in res]

[array([[1071, 3142],
        [1069, 3142],
        [1067, 3145],
        [1062, 3149],
        [1057, 3156],
        [1052, 3164],
        [1048, 3170],
        [1045, 3173],
        [1043, 3177],
        [1041, 3178],
        [1041, 3178]]), array([[1034, 3150],
        [1035, 3152],
        [1038, 3154],
        [1043, 3159],
        [1051, 3167],
        [1056, 3170],
        [1062, 3174],
        [1071, 3177],
        [1081, 3180]]), array([[1086, 3129],
        [1085, 3126],
        [1086, 3124],
        [1089, 3122],
        [1093, 3122],
        [1099, 3122],
        [1103, 3123],
        [1105, 3126],
        [1106, 3131],
        [1104, 3135],
        [1101, 3139],
        [1098, 3143],
        [1094, 3148],
        [1093, 3150],
        [1092, 3150],
        [1093, 3151],
        [1095, 3150],
        [1098, 3151],
        [1103, 3151],
        [1112, 3151]]), array([[1153, 3171],
        [1152, 3171],
        [1150, 3172],
        [1146, 3174],
        [1141, 3173],
       

In [0]:
3*np.array((1, 2))

array([3, 6])

### Normalize investigate

In [0]:
one = training_list[1][3]
one

['8.71113 25.548, 8.69508 25.552, 8.67501 25.5721, 8.63489 25.6082, 8.59476 25.6643, 8.55464 25.7285, 8.52655 25.7767, 8.50248 25.8048, 8.48241 25.8329, 8.47038 25.8449, 8.46636 25.8409',
 '8.4142 25.6162, 8.42223 25.6282, 8.4463 25.6483, 8.48241 25.6884, 8.54661 25.7486, 8.58674 25.7767, 8.63489 25.8128, 8.71113 25.8369, 8.79539 25.861',
 '8.8315 25.4437, 8.82749 25.4196, 8.83551 25.4035, 8.85558 25.3875, 8.88768 25.3835, 8.93583 25.3835, 8.96793 25.3915, 8.98398 25.4196, 8.992 25.4597, 8.97996 25.4958, 8.95589 25.5279, 8.9278 25.56, 8.89971 25.5961, 8.88768 25.6122, 8.88366 25.6162, 8.89169 25.6202, 8.90373 25.6162, 8.93181 25.6202, 8.97194 25.6202, 9.04416 25.6242',
 '9.38121 25.7847, 9.37319 25.7807, 9.35714 25.7927, 9.32504 25.8088, 9.27689 25.8048, 9.23275 25.8008, 9.1846 25.7927, 9.14447 25.7968, 9.10836 25.8008, 9.08027 25.8048',
 '9.19664 25.6603, 9.20065 25.6724, 9.20466 25.6924, 9.2167 25.7326, 9.22874 25.7767, 9.24479 25.8208, 9.26084 25.8529, 9.26886 25.889',
 '9.73431 25.

In [0]:
round(float('8.71113'))

9

In [0]:
tmp = [1, 2, 3]

In [0]:
tmp+[4, 5, 6]

[1, 2, 3, 4, 5, 6]

In [0]:
tmp

[1, 2, 3]

In [0]:
training_list[1]

('Train/INKMLs/Train_2014/formulaire014-equation023.inkml',
 '\\frac{x^{2}+y^{2}}{a^{2}}-\\frac{z^{2}}{c^{2}}+1=0',
 ['f',
  'r',
  'a',
  'c',
  '{',
  'x',
  '^',
  '{',
  '2',
  '}',
  '+',
  'y',
  '^',
  '{',
  '2',
  '}',
  '}',
  '{',
  'a',
  '^',
  '{',
  '2',
  '}',
  '}',
  '-',
  '\\frac',
  '{',
  'z',
  '^',
  '{',
  '2',
  '}',
  '}',
  '{',
  'c',
  '^',
  '{',
  '2',
  '}',
  '}',
  '+',
  '1',
  '=',
  '0'],
 ['8.71113 25.548, 8.69508 25.552, 8.67501 25.5721, 8.63489 25.6082, 8.59476 25.6643, 8.55464 25.7285, 8.52655 25.7767, 8.50248 25.8048, 8.48241 25.8329, 8.47038 25.8449, 8.46636 25.8409',
  '8.4142 25.6162, 8.42223 25.6282, 8.4463 25.6483, 8.48241 25.6884, 8.54661 25.7486, 8.58674 25.7767, 8.63489 25.8128, 8.71113 25.8369, 8.79539 25.861',
  '8.8315 25.4437, 8.82749 25.4196, 8.83551 25.4035, 8.85558 25.3875, 8.88768 25.3835, 8.93583 25.3835, 8.96793 25.3915, 8.98398 25.4196, 8.992 25.4597, 8.97996 25.4958, 8.95589 25.5279, 8.9278 25.56, 8.89971 25.5961, 8.88768 2

In [0]:
tmp.extend([4,5, 6])

In [0]:
tmp

[1, 2, 3, 4, 5, 6]

In [0]:
res = strokearr2poslislis(one)

In [0]:
len(res)

22

In [0]:
res[0]

[(8.71113, 25.548),
 (8.69508, 25.552),
 (8.67501, 25.5721),
 (8.63489, 25.6082),
 (8.59476, 25.6643),
 (8.55464, 25.7285),
 (8.52655, 25.7767),
 (8.50248, 25.8048),
 (8.48241, 25.8329),
 (8.47038, 25.8449),
 (8.46636, 25.8409)]

In [0]:
max(tup[0] for poslis in res for tup in poslis)

15.1913

In [0]:
max(tup[1] for poslis in res for tup in poslis)

26.8761

In [0]:
max(max(tup) for poslis in res for tup in poslis)

26.8761

In [0]:
def strokearr2max(strokearr):
  res = strokearr2poslislis(strokearr)
  return max(max(tup) for poslis in res for tup in poslis)

In [0]:
max(strokearr2max(tup[3]) for tup in valid_success)

1617.0

In [0]:
max(strokearr2max(tup[3]) for tup in train_success)

26406.0

In [0]:
train_max_seqs = [strokearr2max(tup[3]) for tup in train_success]

In [0]:
train_max_seqs[0:3]

[21.8725, 26.8761, 13203.0]

In [0]:
int_train_max_seqs = [n for n in train_max_seqs if int(n) -n == 0]

In [0]:
len(int_train_max_seqs)

5419

In [0]:
float_train_max_seqs = [n for n in train_max_seqs if int(n) -n != 0]

In [0]:
len(float_train_max_seqs)

2771

In [0]:
max(float_train_max_seqs)

32.2729

In [0]:
max(int_train_max_seqs)

26406.0

In [0]:
valid_max_seqs = [strokearr2max(tup[3]) for tup in valid_success]

In [0]:
int_valid_max_seqs = [n for n in valid_max_seqs if int(n) -n == 0]

In [0]:
len(int_valid_max_seqs)

941

In [0]:
len(valid_max_seqs)

952

In [0]:
float_valid_max_seqs = [n for n in valid_max_seqs if int(n) -n != 0]

In [0]:
len(float_valid_max_seqs)

11

In [0]:
max(float_valid_max_seqs)

1496.1021257504324

Data set consists of both int and float.
Float range is vary. But result dataset is also very different size (sometimes, very wide input exists).

I decide to normalize width to 1000 of int.
hight is decided from aspect ratio.

In [0]:
def strokearr2vec(strokearr):
  res = []
  
  for line in strokearr:
    res.extend([(round(float(pair[0])),round(float(pair[1])), INPUT_TYPE_POINT) for pair in [pos.strip().split(" ") for pos in line.split(",")]])
    res.extend([[0, 0, INPUT_TYPE_SEP]])
  res[-1][2] = INPUT_TYPE_END
  return res
    

In [0]:
res = strokearr2vec(one)

In [0]:
len(res)

433

In [0]:
res[0:100]

[(9, 26, 1),
 (9, 26, 1),
 (9, 26, 1),
 (9, 26, 1),
 (9, 26, 1),
 (9, 26, 1),
 (9, 26, 1),
 (9, 26, 1),
 (8, 26, 1),
 (8, 26, 1),
 (8, 26, 1),
 [0, 0, 2],
 (8, 26, 1),
 (8, 26, 1),
 (8, 26, 1),
 (8, 26, 1),
 (9, 26, 1),
 (9, 26, 1),
 (9, 26, 1),
 (9, 26, 1),
 (9, 26, 1),
 [0, 0, 2],
 (9, 25, 1),
 (9, 25, 1),
 (9, 25, 1),
 (9, 25, 1),
 (9, 25, 1),
 (9, 25, 1),
 (9, 25, 1),
 (9, 25, 1),
 (9, 25, 1),
 (9, 25, 1),
 (9, 26, 1),
 (9, 26, 1),
 (9, 26, 1),
 (9, 26, 1),
 (9, 26, 1),
 (9, 26, 1),
 (9, 26, 1),
 (9, 26, 1),
 (9, 26, 1),
 (9, 26, 1),
 [0, 0, 2],
 (9, 26, 1),
 (9, 26, 1),
 (9, 26, 1),
 (9, 26, 1),
 (9, 26, 1),
 (9, 26, 1),
 (9, 26, 1),
 (9, 26, 1),
 (9, 26, 1),
 (9, 26, 1),
 [0, 0, 2],
 (9, 26, 1),
 (9, 26, 1),
 (9, 26, 1),
 (9, 26, 1),
 (9, 26, 1),
 (9, 26, 1),
 (9, 26, 1),
 (9, 26, 1),
 [0, 0, 2],
 (10, 26, 1),
 (10, 26, 1),
 (10, 26, 1),
 (10, 26, 1),
 (10, 26, 1),
 (10, 26, 1),
 (10, 26, 1),
 (10, 26, 1),
 (10, 26, 1),
 (10, 26, 1),
 (10, 26, 1),
 (10, 26, 1),
 (10, 26, 1),
 (10

In [0]:
[pos.strip().split(" ") for pos in one[0].split(",")]

[['8.71113', '25.548'],
 ['8.69508', '25.552'],
 ['8.67501', '25.5721'],
 ['8.63489', '25.6082'],
 ['8.59476', '25.6643'],
 ['8.55464', '25.7285'],
 ['8.52655', '25.7767'],
 ['8.50248', '25.8048'],
 ['8.48241', '25.8329'],
 ['8.47038', '25.8449'],
 ['8.46636', '25.8409']]

In [0]:
valid_success[0]

('valid/TestEM2014GT_INKMLs/29_em_163.inkml',
 'C_t = C + C = 2C',
 ['C', '_', 't', '=', 'C', '+', 'C', '=', '2', 'C'],
 ['248 105, 248 105, 248 105, 248 105, 248 105, 248 105, 248 105, 248 105, 248 105, 248 105, 248 105, 248 105, 248 105, 248 105, 248 105, 248 105, 248 105, 248 105, 248 105, 248 105, 248 105, 248 105, 248 105, 248 105, 246 105, 246 105, 246 105, 246 105, 246 105, 246 105, 246 105, 246 105, 246 105, 246 105, 246 105, 246 105, 246 105, 246 105, 246 105, 246 105, 246 105, 246 105, 246 105, 246 105, 245 105, 245 105, 245 105, 245 105, 245 105, 244 103, 244 103, 244 103, 244 103, 244 103, 244 103, 243 103, 243 103, 243 103, 243 103, 241 102, 241 102, 241 102, 238 102, 234 102, 234 102, 234 102, 230 102, 230 102, 225 103, 225 103, 222 104, 222 104, 222 104, 219 104, 219 104, 219 104, 216 105, 210 108, 210 108, 210 108, 210 108, 210 108, 206 110, 201 113, 201 113, 201 113, 201 113, 201 113, 196 117, 196 117, 194 119, 194 119, 191 123, 191 123, 191 123, 189 126, 189 126, 189 

In [0]:
max(one[3].split(",") valid_success[2][3]

['260 181, 260 180, 262 177, 263 175, 264 174, 266 171, 268 170, 269 170, 271 170, 272 171, 273 173, 273 175, 274 178, 274 181, 274 184, 274 187, 276 192, 278 194, 280 194, 282 195, 287 193, 289 191, 291 188, 292 185, 293 182, 293 179, 293 176, 293 174, 292 172, 291 171, 290 170, 289 171, 288 170, 295 174, 297 174, 299 173, 300 172, 301 171, 300 172, 301 171',
 '321 137, 320 137, 320 136, 322 132, 323 132, 323 133, 323 137, 322 140, 321 142, 319 144, 317 146, 315 147, 313 148, 312 148, 312 147, 314 145, 316 145, 317 146, 319 146, 320 147, 322 148, 324 149, 326 150, 330 148, 332 147, 333 146',
 '366 182, 367 182, 368 182, 367 182, 363 183, 360 183, 356 184, 354 184, 352 185, 350 184, 351 184, 350 184, 348 184',
 '393 176, 392 176, 393 176, 393 175, 396 171, 398 170, 399 170, 401 173, 402 176, 403 183, 404 185, 404 187, 407 190, 409 190, 411 190, 413 189, 415 187, 417 186, 418 184, 419 182, 419 180, 419 177, 419 175, 418 174, 417 173, 418 173, 419 173, 426 172, 428 171',
 '429 206, 429 2

In [0]:
len(res)

477

In [0]:
res[475]

0

In [0]:
one

['8.71113 25.548, 8.69508 25.552, 8.67501 25.5721, 8.63489 25.6082, 8.59476 25.6643, 8.55464 25.7285, 8.52655 25.7767, 8.50248 25.8048, 8.48241 25.8329, 8.47038 25.8449, 8.46636 25.8409',
 '8.4142 25.6162, 8.42223 25.6282, 8.4463 25.6483, 8.48241 25.6884, 8.54661 25.7486, 8.58674 25.7767, 8.63489 25.8128, 8.71113 25.8369, 8.79539 25.861',
 '8.8315 25.4437, 8.82749 25.4196, 8.83551 25.4035, 8.85558 25.3875, 8.88768 25.3835, 8.93583 25.3835, 8.96793 25.3915, 8.98398 25.4196, 8.992 25.4597, 8.97996 25.4958, 8.95589 25.5279, 8.9278 25.56, 8.89971 25.5961, 8.88768 25.6122, 8.88366 25.6162, 8.89169 25.6202, 8.90373 25.6162, 8.93181 25.6202, 8.97194 25.6202, 9.04416 25.6242',
 '9.38121 25.7847, 9.37319 25.7807, 9.35714 25.7927, 9.32504 25.8088, 9.27689 25.8048, 9.23275 25.8008, 9.1846 25.7927, 9.14447 25.7968, 9.10836 25.8008, 9.08027 25.8048',
 '9.19664 25.6603, 9.20065 25.6724, 9.20466 25.6924, 9.2167 25.7326, 9.22874 25.7767, 9.24479 25.8208, 9.26084 25.8529, 9.26886 25.889',
 '9.73431 25.

In [0]:
for i, one_train in enumerate(training_list):
  for 
  encoder_input_data[i]

In [0]:
stroke_length(valid_success[0][3])

1167

In [0]:
len(valid_success[0][3][0].split(","))

152

In [0]:
len(train_failed)

2069

In [0]:
len(train_failed)

1803

In [0]:
len(train_tokenized)

9993

In [0]:
sorted(multi_char_tokens)

['\\Delta',
 '\\alpha',
 '\\beta',
 '\\cdot',
 '\\cdots',
 '\\cos',
 '\\div',
 '\\exists',
 '\\forall',
 '\\frac',
 '\\gamma',
 '\\geq',
 '\\in',
 '\\infty',
 '\\int',
 '\\lambda',
 '\\ldots',
 '\\leq',
 '\\lim',
 '\\limits',
 '\\log',
 '\\mu',
 '\\neq',
 '\\phi',
 '\\pi',
 '\\pm',
 '\\prime',
 '\\rightarrow',
 '\\sigma',
 '\\sin',
 '\\sqrt',
 '\\sum',
 '\\tan',
 '\\theta',
 '\\times',
 '\\{',
 '\\}']

In [0]:
[tup[0] for tup in train_failed if "\\mbox" not in tup[0]]

['{x^{2}} - x - 6 \\lt 0',
 '{ - \\left ( v \\right ) }',
 'a x + b \\lt c',
 '\\left [ 9 \\right ]',
 'a x + b \\lt c',
 '\\lim_{n \\to \\infty} ( x_{n} / y_{n} ) = L_{1} / L_{2}',
 '\\left [ { o } ^ { q } \\right ]',
 '\\cos \\left ( 0 \\right ) = 1',
 '\\tan \\left ( \\frac { \\pi } { 2 } \\right ) = \\infty',
 '\\lim_{n \\to \\infty} ( \\sqrt{n + 2} - \\sqrt{n} ) = 0',
 '\\lim_{y \\to \\infty} y \\sin ( \\frac{c}{y} ) = c',
 '\\log _2 \\left ( 2 ^ 5 \\right ) = 5',
 '\\left| $\\frac{a x_0 + b y_0 + c}{\\sqrt{a^2 + b^2}} \\right|',
 '\\int\\limits_{0}^{\\infty} f ( x ) dx = \\lim_{b \\to \\infty} \\int\\limits_{0}^{b} f ( x ) dx',
 '\\lim_{n \\to \\infty} \\frac{1}{{n^{p}}} = 0',
 '\\left ( 2 \\right )',
 '1234 + 5678 \\gt 90',
 '\\lim_{n \\to \\infty} \\frac{n !}{\\sqrt{2 \\pi n} ( \\frac{n}{e} )} = 1',
 '\\cos \\left ( 0 \\right ) = 1',
 'a x + b \\lt c',
 '\\lim_{n \\to \\infty} \\frac{n !}{\\sqrt{2 \\pi n} ( \\frac{n}{e} )} = 1',
 '\\left ( 3 \\right )',
 '\\lim_{n \\to \\infty}

\\left (, \\right )を直せば結構減りそう。
\\to もtokenに追加。

In [0]:
filter_mathrm('a_x + 2^2')

'a_x + 2^2'

In [0]:
filter_mathrm('R_\\mathrm{L}')

'R_L'

In [0]:
tokenizer.tokenize_all(filter_trim_exclamation('u^2 = {u_1}^2 + {u_2}^2 + {u_3}^2 \\!'))

(True,
 ['u',
  '^',
  '2',
  '=',
  '{',
  'u',
  '_',
  '1',
  '}',
  '^',
  '2',
  '+',
  '{',
  'u',
  '_',
  '2',
  '}',
  '^',
  '2',
  '+',
  '{',
  'u',
  '_',
  '3',
  '}',
  '^',
  '2'])

'R_\x01'

In [0]:
failed

[('q+w\\;', 'valid/TestEM2014GT_INKMLs/31_em_178.inkml'),
 (' | x \\parallel y | = | x y | ',
  'valid/TestEM2014GT_INKMLs/RIT_2014_198.inkml'),
 (' \\mbox{all }z ', 'valid/TestEM2014GT_INKMLs/512_em_297.inkml'),
 (' y \\gt z ', 'valid/TestEM2014GT_INKMLs/RIT_2014_93.inkml'),
 (' r \\! \\times \\! n ', 'valid/TestEM2014GT_INKMLs/518_em_418.inkml'),
 ('\\ $10,000 + $1,000 = $11,000', 'valid/TestEM2014GT_INKMLs/26_em_99.inkml'),
 ('\\left (  \\left ( \\frac{1}{4} \\left ( 3 \\right )^4 - 3 \\left ( 3 \\right )^2 \\right ) - \\left ( \\frac{1}{4} \\left ( 2 \\right )^4 - 3 \\left ( 2 \\right )^2 \\right )  \\right )',
  'valid/TestEM2014GT_INKMLs/519_em_448.inkml'),
 ('R_o=\\frac{\\left( \\frac{\\beta + 1}{\\beta} \\right)r_e+ \\left(\\beta + 2 +\\frac{2}{\\beta}\\right)r_{o}}{2 + \\frac{2}${\\beta}}',
  'valid/TestEM2014GT_INKMLs/20_em_27.inkml'),
 ('\\Delta x\\Delta k \\geq 1/2', 'valid/TestEM2014GT_INKMLs/34_em_239.inkml'),
 ('\\pi d\\ = 2\\pi r', 'valid/TestEM2014GT_INKMLs/513_em_304.

In [0]:
MATH_RM_PAT.search(' u_{\\mathrm{m}} ')

<_sre.SRE_Match object; span=(4, 14), match='\\mathrm{m}'>

In [0]:
valid_mathrm = [(dic["path"], dic["latex"]) for dic in valid_dicts if MATH_RM_PAT.search(dic["latex"])]

In [0]:
valid_mathrm

[('valid/TestEM2014GT_INKMLs/502_em_12.inkml', 'R_\\mathrm{L}'),
 ('valid/TestEM2014GT_INKMLs/518_em_433.inkml', '\\mathrm{M}^n'),
 ('valid/TestEM2014GT_INKMLs/20_em_33.inkml',
  'R_\\mathrm{a} = \\frac{R_1R_2 + R_2R_3 + R_3R_1}{R_2}'),
 ('valid/TestEM2014GT_INKMLs/500_em_109.inkml', 'b_\\mathrm{L}'),
 ('valid/TestEM2014GT_INKMLs/20_em_30.inkml', 'I_\\mathrm{S}'),
 ('valid/TestEM2014GT_INKMLs/516_em_393.inkml', '\\!\\mathrm{Nm}'),
 ('valid/TestEM2014GT_INKMLs/514_em_346.inkml', '\\!\\mathrm{m}^2'),
 ('valid/TestEM2014GT_INKMLs/27_em_112.inkml', '\\mathrm{M}_3'),
 ('valid/TestEM2014GT_INKMLs/518_em_423.inkml', ' u_{\\mathrm{m}} '),
 ('valid/TestEM2014GT_INKMLs/501_em_3.inkml', 'k_\\mathrm{e}'),
 ('valid/TestEM2014GT_INKMLs/515_em_368.inkml', '\\mathrm{Im}'),
 ('valid/TestEM2014GT_INKMLs/517_em_404.inkml', '\\mathrm{Pa}'),
 ('valid/TestEM2014GT_INKMLs/32_em_215.inkml', '\\!\\mathrm{m}^3'),
 ('valid/TestEM2014GT_INKMLs/515_em_360.inkml', '\\mathrm{C}^{\\alpha}'),
 ('valid/TestEM2014GT_INK

In [0]:
train_mathrm = [(dic["path"], dic["latex"]) for dic in train_dicts if MATH_RM_PAT.search(dic["latex"])]

In [0]:
train_mathrm

[('Train/INKMLs/TestINKMLGT_2013/106_em_104.inkml',
  'z=|z|\\mathrm{e}^{i\\theta}'),
 ('Train/INKMLs/TestINKMLGT_2013/124_em_403.inkml',
  'w_k^2 = |z|\\mathrm{e}^{i\\theta} \\mathrm{e}^{2i\\pi k} = z'),
 ('Train/INKMLs/TestINKMLGT_2013/122_em_350.inkml',
  'L=2^{1/4} \\mathrm{m}=118,9 \\mathrm{cm}'),
 ('Train/INKMLs/TestINKMLGT_2013/127_em_497.inkml',
  '\\mathrm{Var}[X_i] = \\frac{\\alpha_i (\\alpha_0-\\alpha_i)}{\\alpha_0^2 (\\alpha_0+1)}'),
 ('Train/INKMLs/TestINKMLGT_2013/105_em_68.inkml',
  '\\mathrm{card}(B^A) = 2^{\\mathrm{card}(A)}'),
 ('Train/INKMLs/TestINKMLGT_2013/118_em_242.inkml',
  '\\frac{\\sin{\\theta}}{v}= \\mathrm{Cste}'),
 ('Train/INKMLs/TestINKMLGT_2013/128_em_529.inkml', 'T_{\\mathrm{moy}}=10'),
 ('Train/INKMLs/TestINKMLGT_2013/126_em_454.inkml',
  'G=10 \\log \\left( {\\frac{V_{s}}{V_{e}}} \\right)^2 \\mathrm{dB}')]

In [0]:
len(train_dicts)

9993

In [0]:
train_dicts[0:2]

[{'latex': 'f_2, g_2',
  'path': 'Train/INKMLs/Train_2014/formulaire028-equation067.inkml',
  'strokes': ['10.7816 21.4071, 10.7776 21.3991, 10.7896 21.4031, 10.8097 21.4071, 10.8418 21.3951, 10.9019 21.375, 10.9782 21.3309, 11.0705 21.2867, 11.1226 21.2386, 11.1587 21.1904, 11.1708 21.1342, 11.1708 21.066, 11.1427 20.9858, 11.1066 20.9296, 11.0825 20.9176, 11.0745 20.9216, 11.0624 20.9336, 11.0464 20.9978, 11.0263 21.062, 11.0303 21.1503, 11.0384 21.2426, 11.0544 21.3268, 11.0705 21.4392, 11.0785 21.5235, 11.0865 21.5877, 11.0865 21.6398, 11.0905 21.6639, 11.0945 21.688, 11.0905 21.688',
   '11.0063 21.4793, 11.0103 21.4753, 11.0143 21.4753, 11.0344 21.4713, 11.0865 21.4673, 11.1467 21.4633, 11.2591 21.4472',
   '11.5199 21.4472, 11.4958 21.4472, 11.4757 21.4472, 11.4557 21.4352, 11.4476 21.4352, 11.4396 21.4151, 11.4436 21.3991, 11.4517 21.387, 11.4677 21.367, 11.4958 21.363, 11.5159 21.375, 11.5439 21.383, 11.552 21.4071, 11.552 21.4272, 11.5319 21.4352, 11.4918 21.4753, 11.4476 21.

In [0]:
tokenizer.tokenize_all(' \\frac {\\log _ {b} x} {\\log _ {b} a} ')

(True,
 ['\\frac',
  '{',
  '\\log',
  '_',
  '{',
  'b',
  '}',
  'x',
  '}',
  '{',
  '\\log',
  '_',
  '{',
  'b',
  '}',
  'a',
  '}'])

In [0]:
tokenizer.set_target(' \\frac {\\log _ {b} x} {\\log _ {b} a} ')

In [0]:
tokenizer.skip_space()

In [0]:
tokenizer.tokenize_one()

'\\frac'

In [0]:
tokenizer.tokenize_one()

'{'

In [0]:
tokenizer.tokenize_one()

'\\log'

In [0]:
tokenizer.tokenize_one()

'_'

In [0]:
tokenizer.tokenize_one()

'{'

In [0]:
tokenizer.tokenize_one()

'b'

In [0]:
tokenizer.tokenize_one()

'}'

In [0]:
tokenizer.tokenize_one()

'x'

In [0]:
tokenizer.tokenize_one()

'}'

In [0]:
tokenizer.tokenize_one()

'{'

In [0]:
tokenizer.tokenize_one()

'\\log'

In [0]:
tokenizer.tokenize_one()

'_'

In [0]:
tokenizer.tokenize_one()

'{'

In [0]:
tokenizer.tokenize_one()

'b'

In [0]:
tokenizer.tokenize_one()

'}'

In [0]:
tokenizer.tokenize_one()

'a'

In [0]:
tokenizer.tokenize_one()

IndexError: ignored

In [0]:
tokenizer.unknown

'\\'

In [0]:
multi_char_tokens

['\\geq',
 '\\sqrt',
 '\\leq',
 '\\infty',
 '\\cdot',
 '\\sigma',
 '\\pm',
 '\\log',
 '\\pi',
 '\\limits',
 '\\}',
 '\\tan',
 '\\gamma',
 '\\{',
 '\\theta',
 '\\forall',
 '\\int',
 '\\sin',
 '\\prime',
 '\\ldots',
 '\\cdots',
 '\\cos',
 '\\Delta',
 '\\neq',
 '\\in',
 '\\alpha',
 '\\times',
 '\\lim',
 '\\lambda',
 '\\exists',
 '\\frac',
 '\\rightarrow',
 '\\div',
 '\\phi',
 '\\beta',
 '\\mu',
 '\\sum']

In [0]:
failed

[('q+w\\;', 'valid/TestEM2014GT_INKMLs/31_em_178.inkml'),
 (' \\frac {\\log _ {b} x} {\\log _ {b} a} ',
  'valid/TestEM2014GT_INKMLs/RIT_2014_192.inkml'),
 (' (a (b ^ {2})) + (d ^ {3}) ',
  'valid/TestEM2014GT_INKMLs/RIT_2014_147.inkml'),
 ('R_\\mathrm{L}', 'valid/TestEM2014GT_INKMLs/502_em_12.inkml'),
 (' a,\\ldots,f ', 'valid/TestEM2014GT_INKMLs/512_em_295.inkml'),
 (' \\{ 7, 7 \\} = \\{ 7 \\} ', 'valid/TestEM2014GT_INKMLs/RIT_2014_73.inkml'),
 ('\\mathrm{M}^n', 'valid/TestEM2014GT_INKMLs/518_em_433.inkml'),
 ('u^2 = {u_1}^2 + {u_2}^2 + {u_3}^2 \\!',
  'valid/TestEM2014GT_INKMLs/510_em_104.inkml'),
 (' a - \\frac {3} {a} + \\frac {1} {a ^ {2} + 1} ',
  'valid/TestEM2014GT_INKMLs/RIT_2014_26.inkml'),
 (' x ^ {2} (x - 1) (x ^ {2} + x + 1) + (x ^ {2} + x + 1) ',
  'valid/TestEM2014GT_INKMLs/RIT_2014_194.inkml'),
 (' \\frac {1} {9} ', 'valid/TestEM2014GT_INKMLs/RIT_2014_154.inkml'),
 (' \\frac {4 + 4} {4 + 4} ', 'valid/TestEM2014GT_INKMLs/RIT_2014_88.inkml'),
 (' \\cos 3 \\theta = 4 \\co

In [0]:
valid_tokenized

[('valid/TestEM2014GT_INKMLs/29_em_163.inkml', (False, None)),
 ('valid/TestEM2014GT_INKMLs/31_em_178.inkml', (False, None)),
 ('valid/TestEM2014GT_INKMLs/RIT_2014_192.inkml', (False, None)),
 ('valid/TestEM2014GT_INKMLs/502_em_16.inkml', (False, None)),
 ('valid/TestEM2014GT_INKMLs/520_em_466.inkml', (False, None)),
 ('valid/TestEM2014GT_INKMLs/RIT_2014_147.inkml', (False, None)),
 ('valid/TestEM2014GT_INKMLs/502_em_12.inkml', (False, None)),
 ('valid/TestEM2014GT_INKMLs/519_em_440.inkml',
  (True,
   ['\\frac', '{', '8', '9', '9', '3', '}', '{', '7', '8', '7', '3', '}'])),
 ('valid/TestEM2014GT_INKMLs/512_em_295.inkml', (False, None)),
 ('valid/TestEM2014GT_INKMLs/510_em_100.inkml', (False, None)),
 ('valid/TestEM2014GT_INKMLs/29_em_173.inkml',
  (True,
   ['\\frac',
    '{',
    'x',
    '^',
    '2',
    '+',
    '1',
    '3',
    'x',
    '+',
    '4',
    '0',
    '}',
    '{',
    '2',
    'x',
    '^',
    '3',
    '+',
    '2',
    '7',
    'x',
    '^',
    '2',
    '+',
    

In [0]:
tokenizer.unknown

AttributeError: ignored

In [0]:
tokenizer.set_target("abc space")

In [0]:
tokenizer.go_next("ab")

'ab'

In [0]:
tokenizer.target[tokenizer.pos]

'c'

In [0]:
tokenizer.skip_space()

In [0]:
tokenizer.pos

2

In [0]:
tokenizer.pos = 3

In [0]:
target = "\\geqabc"

In [0]:
token = multi_char_tokens[0]

In [0]:
target.startswith(token)

False

In [0]:
multi_char_tokens[0:5]

['\\geq', '\\sqrt', '\\leq', '\\infty', '\\cdot']

In [0]:
onechset = set(one_char_tokens)

In [0]:
"!" in onechset

True

In [0]:
len(multi_char_tokens)

39

In [0]:
len(one_char_tokens)

73

In [0]:
one_char_tokens[0:3]

['/', '(', ',']

In [0]:
match = STROKE_PAT.search(text)

In [0]:
match

<_sre.SRE_Match object; span=(1190, 4887), match='<trace id="0">\n34 54, 34 54, 34 54, 34 54, 34 54>

In [0]:
match.group(1).strip("\n")

'34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 34 54, 35 53, 35 53, 35 53, 35 53, 35 52, 35 52, 35 52, 35 52, 35 52, 35 52, 35 52, 35 52, 35 52, 35 52, 35 52, 35 52, 35 52, 35 52, 35 52, 35 52, 35 52, 35 52, 35 52, 36 50, 36 50, 36 50, 36 50, 37 49, 37 49, 37 49, 37 49, 37 49, 37 49, 37 49, 37 49, 37 49, 37 49, 37 49, 37 49, 37 49, 37 49, 37 49, 37 49, 37 49, 39 49, 39 49, 39 49, 40 48, 40 48, 40 48, 40 48, 40 48, 40 48, 40 48, 40 48, 40 48, 40 48, 40 48, 40 48, 40 48, 40 48, 40 48, 42 47, 42 47, 42 47, 42 47, 42 47, 42 47, 42 47, 42 47, 44 47, 44 47, 44 47, 44 47, 44 47, 45 47, 45 47, 45 47, 45 47, 45 47, 45 47, 46 47, 46 47, 46 47, 46 47, 46 47, 46 47, 46 47, 46 47, 46 47, 46 47, 46 47, 46 47

In [0]:
match.end()

4887

In [0]:
LATEX_PAT.search(text).group(1).strip()

'x_k xx_k + y_k yx_k'

In [0]:
f = open(one_file, "r")

In [0]:
lines = [line.rstrip("\n") for line in f]

In [0]:
len(lines)

159

In [0]:
lines[10]

'<annotation type="UI">ISICAL_2014_F18_E0</annotation>'

In [0]:
f.close()

In [0]:
with open(one_file, "r") as f:
  f.readlines

In [0]:
from google.colab import auth
auth.authenticate_user()


For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.



In [0]:
# !gsutil cp gs://karino2-tegashiki/dataset/offline-test.pkl.gz ./
# !gsutil cp gs://karino2-tegashiki/dataset/offline-train.pkl.gz ./
# !gsutil cp gs://karino2-tegashiki/dataset/test_caption.txt.gz ./
!gsutil cp gs://karino2-tegashiki/dataset/train_caption.txt.gz ./
!gsutil cp gs://karino2-tegashiki/dataset/dictionary.txt.gz ./
# offline-train-features.pkl.gz
!gsutil cp gs://karino2-tegashiki/dataset/train-features-100.pkl.gz ./

Copying gs://karino2-tegashiki/dataset/train_caption.txt.gz...
/ [1 files][ 98.1 KiB/ 98.1 KiB]                                                
Operation completed over 1 objects/98.1 KiB.                                     
Copying gs://karino2-tegashiki/dataset/dictionary.txt.gz...
/ [1 files][  539.0 B/  539.0 B]                                                
Operation completed over 1 objects/539.0 B.                                      
Copying gs://karino2-tegashiki/dataset/train-features-100.pkl.gz...
/ [1 files][  3.2 MiB/  3.2 MiB]                                                
Operation completed over 1 objects/3.2 MiB.                                      


In [0]:
with gzip.open("dictionary.txt.gz", "rt") as f:
  sym2id = {tup[0]:int(tup[1]) for tup in [line.rstrip().split() for line in f]}

In [0]:
list(sym2id.items())[0:5]

[('\\geq', 1), ('\\sqrt', 2), ('\\leq', 3), ('/', 4), ('\\infty', 5)]

In [0]:
def rawlabels2df(rawlabelparis):
  label_id_dict = {tup[0]: ",".join(map(lambda x:str(sym2id[x]), tup[1].split())) for tup in rawlabelparis}
  return pd.DataFrame(label_id_dict.items(), columns=["file", "exp_ids"])

In [0]:
with gzip.open("train_caption.txt.gz", "rt") as f:
  train_raw_labelpair = [line.rstrip().split("\t") for line in f]

In [0]:
train_labels = rawlabels2df(train_raw_labelpair)

In [0]:
train_labels.head()

file                                            exp_ids
0  formulaire004-equation047  77,6,29,88,93,105,47,57,79,93,89,5,110,75,57,5...
1  formulaire026-equation071  77,6,29,47,57,90,110,88,3,77,6,29,47,57,65,110,88
2  formulaire030-equation000                       90,91,68,34,90,37,3,90,66,38
3                  MfrDB2656                             83,57,65,110,57,68,110
4            200924-1331-237                              104,34,70,82,78,34,29

In [0]:
train_labels["exp_ids"].map(lambda x: len(x.split(","))).max()

96

In [0]:
len(train_labels)

8835

In [0]:
with gzip.open("train-features-100.pkl.gz",'rb') as f:
    raw_dict = pickle.load(f)
    train_features = {key: np.squeeze(raw_dict[key], axis=0) for key in raw_dict.keys()} 

In [0]:
# samples is list of (W, H, 1280) nparrays
def pad_batch_wh(samples, maxw, maxh):
  w_padded = [preprocessing.sequence.pad_sequences(arr, maxlen=maxh, padding='post', value=np.nan) for arr in samples]
  perm_ax = [np.moveaxis(arr, 0, 1) for arr in w_padded]
  perm_padded =[preprocessing.sequence.pad_sequences(arr, maxlen=maxw, padding='post', value=np.nan) for arr in perm_ax]
  return [np.moveaxis(arr, 0, 1) for arr in perm_padded]

def pad_batch(samples):
  maxw = np.max([v.shape[0] for v in samples])
  maxh = np.max([v.shape[1] for v in samples])
  return pad_batch_wh(saples, maxw, maxh)

### Setup decoder input and target for training

In [0]:
BEGIN_OF_SEQ = 111
END_OF_SEQ=0

# MAX_TEX_LEN=220
# +2 is bos, eos
MAX_TRAIN_LEN=96+2

VOCAB_SIZE=112

In [0]:
# TPU need to specify width and height.
# This is not a whole training set. I'll update once I load whole training set features.
MAX_W = 36
MAX_H = 6

In [0]:
decoder_input_data = np.zeros(
    (len(train_labels), MAX_TRAIN_LEN),
    dtype='uint8')

In [0]:
decoder_target_data = np.zeros(
    (len(train_labels), MAX_TRAIN_LEN, VOCAB_SIZE),
    dtype='uint8')

In [0]:
for i, row in train_labels.iterrows():
    seq = [BEGIN_OF_SEQ] + [int(s) for s in row['exp_ids'].split(",")]
    decoder_input_data[i, 0:len(seq)] =seq
    decoder_target_data[i, 0:(len(seq)-1), :] =  np.eye(VOCAB_SIZE)[decoder_input_data[i, 1:len(seq)]]

In [0]:
decoder_input_data.shape

(8835, 98)

In [0]:
decoder_target_data.shape

(8835, 98, 112)

In [0]:
decoder_input_data[0, 0:5]

array([111,  77,   6,  29,  88], dtype=uint8)

In [0]:
decoder_target_data[0, 0:3, 5:30]

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1]], dtype=uint8)